trigger:
  - main

pr:
  - main

variables:
  - group: Main variables for all pipelines
  - group: sonar-cloud-config

resources:
  repositories:
    - repository: templates
      type: github
      name: juntossomosmais/azure-pipelines-templates
      endpoint: github.com
      ref: refactor/change-folder-structure-dotnet

extends:
  template: dotnet/nuget_deploy_artifacts.yaml@templates
  parameters:
    SonarProject: "juntossomosmais_csharp-rest-framework"
    AzureFeedId: "7a82b4a3-6db8-4249-a7ec-9968996b9406/0d3df630-9f80-4d07-b31c-822063ea1dd0"
    AzurePackageId: "46a8a833-03d0-4d89-97f4-4ef2fc850e13"
    DotnetVersion: "6.0.x"