version: "3.8"
services:
  mssql-server-2019-latest:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"

  integration-tests:
    container_name: csharp-rest-framework-integration-tests
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql-server-2019-latest
    environment:
      - "ConnectionStrings__DefaultConnectionString=Data Source=mssql-server-2019-latest,1433;Initial Catalog=POCContext;User Id=sa;Password=Password1"
    command:
      [
        "./Scripts/start-tests.sh"
      ]
