version: "3.6"
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
      # Developer / Express / Standard / Enterprise  / EnterpriseCore
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./scripts/start-tests.sh:/app/scripts/start-tests.sh
    environment:
      - "ConnectionStrings__DefaultConnectionString=Data Source=sqlserver,1433;Initial Catalog=RestFramework;User Id=sa;Password=Password1"
    command: [ "./scripts/start-tests.sh" ]

  lint-formatter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # Uncomment the following line to run the checker
    # command: [ "./scripts/start-check-formatting.sh" ]
    # Uncomment the following line to run the formatter
    command: [ "./scripts/start-formatter.sh" ]
