name: Publish package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Generate package
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          dotnet pack -c Release -o out -p:PackageVersion=$TAG_NAME
      - name: Push package
        run: |
          dotnet nuget push out/*.nupkg \
          --api-key ${{ secrets.PUBLIC_NUGET_API_KEY }} \
          --source "https://api.nuget.org/v3/index.json" \
          --skip-duplicate
