name: Publish coverage report

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.sln'
      - 'Directory.Build.props'
  workflow_dispatch:

jobs:
  publish-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Install dotnet-sonarscanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
      - name: Build the project, run all tests and publish to SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PROJECT_VERSION: ${{ github.sha }}
          SOURCE_BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -e
          docker compose up -d db
          ./scripts/start-sonarcloud.sh
